const mineType = {
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  mpp: 'application/vnd.ms-project',
  js: 'text/javascript',
  json: 'application/json',
  ico: 'image/x-icon',
  zip: 'application/x-zip-compressed',
  pdf: 'application/pdf',
  tgz: 'application/x-compressed',
  exe: 'application/x-msdownload',
  mp4: 'video/mp4',
};
